spring:
  config:
    activate:
      on-profile: docker
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
  data:
    redis:
      host: ${REDIS_SERVER}
      port: ${REDIS_PORT}
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      bootstrap-servers: ${KAFKA_SERVER}
      properties:
        security.protocol: PLAINTEXT
        # 클라이언트 설정 세부화
        max.block.ms: 5000                 # 메타데이터 요청 타임아웃
        reconnect.backoff.ms: 1000         # 재연결 시도 간격
        reconnect.backoff.max.ms: 10000    # 최대 재연결 시도 간격
        retry.backoff.ms: 1000             # 재시도 간격
        request.timeout.ms: 30000          # 요청 타임아웃
        connections.max.idle.ms: 540000    # 연결 유지 시간
  mail:
    host: smtp.naver.com
    username: ${OWNER_EMAIL}
    password: ${OWNER_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
super-user:
  email: ${ADMIN_EMAIL}