spring:
  config:
    activate:
      on-profile: docker
    import: file:${user.home}/ngt_project/ticketing-payment/infra/src/main/resources/application.yml

toss:
  secret-key: dGVzdF9nc2tfZG9jc19PYVB6OEw1S2RtUVhrelJ6M3k0N0JNdzY6Cg==
  host: https://api.tosspayments.com

