spring:
  config:
    activate:
      on-profile: docker
    import: file:${user.home}/ngt_project/ticketing-payment/infra/src/main/resources/application.yml

toss:
  secret-key: ${PAYMENT_SECRET_KEY}
  host: https://api.tosspayments.com

